version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: assistant_local
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database       
      MYSQL_USER: my_user               
      MYSQL_PASSWORD: my_password       
    volumes:
      - ~/db_data:/var/lib/mysql

volumes:
  db_data:
    driver: local
